"""empty message

Revision ID: ae9fed6597e5
Revises: None
Create Date: 2016-11-10 01:09:13.918399

"""

# revision identifiers, used by Alembic.
revision = 'ae9fed6597e5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('domain')
    op.drop_table('organization')
    op.drop_table('proposals')
    op.drop_table('position')
    op.drop_table('role')
    op.drop_table('category')
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('category',
    sa.Column('idCategory', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idCategory', name=u'category_pkey')
    )
    op.create_table('role',
    sa.Column('roleID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('roleID', name=u'role_pkey')
    )
    op.create_table('position',
    sa.Column('idPosition', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dateStart', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dateEnd', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('positionLink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idPosition', name=u'position_pkey')
    )
    op.create_table('proposals',
    sa.Column('idProposal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposalDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('proposalLink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idProposal', name=u'proposals_pkey')
    )
    op.create_table('organization',
    sa.Column('idOrganization', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('publicName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completeName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idOrganization', name=u'organization_pkey')
    )
    op.create_table('domain',
    sa.Column('idDomain', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('officialName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('domainLink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idDomain', name=u'domain_pkey')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'posts_pkey')
    )
    ### end Alembic commands ###
