language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "python manage.py test"

services:
  - postgresql

before_script:
  - cp database.travis.yml database.yml
  - psql -c 'create database polex;' -U luiscosta

