"""empty message

Revision ID: 17f071f185ea
Revises: None
Create Date: 2016-11-30 12:23:17.827138

"""

# revision identifiers, used by Alembic.
revision = '17f071f185ea'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('idOrganization', sa.Integer(), nullable=False),
    sa.Column('publicName', sa.String(length=150), nullable=True),
    sa.Column('completeName', sa.String(length=300), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('idOrganization')
    )
    op.create_table('position',
    sa.Column('idPosition', sa.Integer(), nullable=False),
    sa.Column('namePosition', sa.String(length=120), nullable=True),
    sa.Column('dateStart', sa.Date(), nullable=True),
    sa.Column('dateEnd', sa.Date(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idPosition')
    )
    op.create_table('role',
    sa.Column('idRole', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idRole')
    )
    op.create_table('domain',
    sa.Column('idDomain', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('officialName', sa.String(length=200), nullable=True),
    sa.Column('publicBioLink', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idDomain')
    )
    op.create_table('category',
    sa.Column('idCategory', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('idCategory')
    )
    op.create_table('post',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['politics.idPolitician'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.drop_table('posts')
    op.drop_table('politiciansComments')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politiciansComments',
    sa.Column('uid', sa.INTEGER(), server_default=sa.text(u'nextval(\'"politiciansComments_uid_seq"\'::regclass)'), nullable=False),
    sa.Column('cid', sa.INTEGER(), server_default=sa.text(u'nextval(\'"politiciansComments_cid_seq"\'::regclass)'), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('time', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], [u'users.uid'], name=u'politiciansComments_uid_fkey'),
    sa.PrimaryKeyConstraint('cid', name=u'politiciansComments_pkey')
    )
    op.create_table('posts',
    sa.Column('cid', sa.INTEGER(), nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pid'], [u'politics.idPolitician'], name=u'posts_pid_fkey'),
    sa.PrimaryKeyConstraint('cid', name=u'posts_pkey')
    )
    op.drop_table('post')
    op.drop_table('category')
    op.drop_table('domain')
    op.drop_table('role')
    op.drop_table('position')
    op.drop_table('organization')
    ### end Alembic commands ###
