"""empty message

Revision ID: 4ef17bbe76c9
Revises: None
Create Date: 2016-12-01 01:54:19.158363

"""

# revision identifiers, used by Alembic.
revision = '4ef17bbe76c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('idOrganization', sa.Integer(), nullable=False),
    sa.Column('publicName', sa.String(length=150), nullable=True),
    sa.Column('completeName', sa.String(length=300), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('idOrganization')
    )
    op.create_table('proposals',
    sa.Column('idProposal', sa.Integer(), nullable=False),
    sa.Column('nameProposal', sa.String(length=120), nullable=True),
    sa.Column('dateProposal', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('linkProposal', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idProposal')
    )
    op.create_table('position',
    sa.Column('idPosition', sa.Integer(), nullable=False),
    sa.Column('namePosition', sa.String(length=120), nullable=True),
    sa.Column('dateStart', sa.Date(), nullable=True),
    sa.Column('dateEnd', sa.Date(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idPosition')
    )
    op.create_table('politics',
    sa.Column('idPolitician', sa.Integer(), nullable=False),
    sa.Column('publicName', sa.String(length=150), nullable=True),
    sa.Column('completeName', sa.String(length=300), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('idPolitician')
    )
    op.create_table('domain',
    sa.Column('idDomain', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('officialName', sa.String(length=200), nullable=True),
    sa.Column('publicBioLink', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idDomain')
    )
    op.create_table('category',
    sa.Column('idCategory', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('idCategory')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('pwdhash', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role',
    sa.Column('idRole', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idRole')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('users')
    op.drop_table('category')
    op.drop_table('domain')
    op.drop_table('politics')
    op.drop_table('position')
    op.drop_table('proposals')
    op.drop_table('organization')
    ### end Alembic commands ###
