"""empty message

Revision ID: c6a878da054d
Revises: e44510af0f40
Create Date: 2016-11-17 23:09:23.489617

"""

# revision identifiers, used by Alembic.
revision = 'c6a878da054d'
down_revision = 'e44510af0f40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('idOrganization', sa.Integer(), nullable=False),
    sa.Column('publicName', sa.String(length=150), nullable=True),
    sa.Column('completeName', sa.String(length=300), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('idOrganization')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    ### end Alembic commands ###
