"""empty message

Revision ID: ce3d25012297
Revises: None
Create Date: 2016-11-10 16:47:53.072311

"""

# revision identifiers, used by Alembic.
revision = 'ce3d25012297'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politics',
    sa.Column('idPolitician', sa.Integer(), nullable=False),
    sa.Column('publicName', sa.String(length=150), nullable=True),
    sa.Column('completeName', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('idPolitician')
    )
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column(u'users', 'firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column(u'users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'users', 'pwdhash',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column(u'users', 'pwdhash',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column(u'users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(u'users', 'firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_table('politics')
    ### end Alembic commands ###
