"""empty message

Revision ID: df054929034e
Revises: 17f071f185ea
Create Date: 2016-11-30 12:45:24.262882

"""

# revision identifiers, used by Alembic.
revision = 'df054929034e'
down_revision = '17f071f185ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint(u'post_pid_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'pid')
    op.drop_column('post', 'cid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cid', sa.INTEGER(), nullable=False))
    op.add_column('post', sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'post_pid_fkey', 'post', 'politics', ['pid'], ['idPolitician'])
    op.drop_column('post', 'id')
    ### end Alembic commands ###
